services:
  db:
    image: postgres:16
    container_name: mtuface_db
    environment:
      POSTGRES_DB: mtuface
      POSTGRES_USER: mtu
      POSTGRES_PASSWORD: mtu123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: ./backend
    container_name: mtuface_api
    env_file:
      - ./backend/.env.example
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./evidence:/app/evidence

volumes:
  pgdata:
